# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Andrew Hemans"
email: andrewhemans@gmail.com
description: "Andrew Hemans: Product Designer, Front-end Developer, Builder of things."
baseurl:
url: https://andrewhemans.github.io/portfolio-new 
twitter_username: andrewhemans
github_username:  andrewhemans
linkedin_username:  andrewhemans

# Build settings
markdown: kramdown
